// Spaces Slice - Manages workspace/space listings
import { createSlice } from '@reduxjs/toolkit';

// Mock spaces data
const initialSpaces = [
  {
    id: 1,
    name: 'Downtown Office Suite',
    description: 'Professional office suite in the heart of downtown with modern amenities and stunning city views. Perfect for small teams and startups.',
    type: 'office',
    category: 'Office Space',
    price: 150,
    priceUnit: 'day',
    capacity: 10,
    location: '123 Main St, Nairobi - CBD',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    amenities: ['WiFi', 'Parking', 'Meeting Room', 'Kitchen', 'Air Conditioning'],
    rating: 4.8,
    reviews: 24,
       available: true,
    featured: true,
  },
  {
    id: 2,
    name: 'Creative Studio Loft',
    description: 'Spacious and bright loft space perfect for creative professionals, photo shoots, and artistic endeavors. Natural light throughout.',
    type: 'studio',
    category: 'Creative Studio',
    price: 75,
    priceUnit: 'hour',
    capacity: 15,
    location: '456 Art Ave, Nairobi - Kilimani',
    image: 'https://images.unsplash.com/photo-1505373877841-8d43a716668d?w=800&q=80',
    amenities: ['WiFi', 'Equipment Rental', 'Props', 'Lighting', 'Green Screen'],
    rating: 4.9,
    reviews: 18,
    available: true,
    featured: true,
  },
  {
       id: 3,
    name: 'Conference Center',
    description: 'State-of-the-art conference facility with AV equipment, breakout rooms, and professional catering options.',
    type: 'conference',
    category: 'Conference Room',
    price: 500,
    priceUnit: 'day',
    capacity: 100,
    location: '789 Business Blvd, Nairobi - Westlands',
    image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800&q=80',
    amenities: ['WiFi', 'AV Equipment', 'Catering', 'Parking', 'Security'],
    rating: 4.7,
    reviews: 42,
    available: true,
    featured: false,
  },
  {
    id: 4,
    name: 'Co-Working Desk',
    description: 'Flexible co-working space with dedicated desk, high-speed internet, and access to all community amenities.',
    type: 'coworking',
    category: 'Co-Working Space',
    price: 299,
    priceUnit: 'month',
    capacity: 1,
    location: '321 Startup Lane, Nairobi - Runda',
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80',
    amenities: ['WiFi', 'Desk', 'Locker', 'Coffee', 'Meeting Room Access'],
    rating: 4.6,
    reviews: 67,
    available: true,
    featured: true,
  },
  {
    id: 5,
    name: 'Wellness Studio',   id: 3,
    name: 'Conference Center',
    description: 'State-of-the-art conference facility with AV equipment, breakout rooms, and professional catering options.',
    type: 'conference',
    category: 'Conference Room',
    price: 500,
    priceUnit: 'day',
    capacity: 100,
    location: '789 Business Blvd, Nairobi - Westlands',
    image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800&q=80',
    amenities: ['WiFi', 'AV Equipment', 'Catering', 'Parking', 'Security'],
    rating: 4.7,
    reviews: 42,
    available: true,
    featured: false,
  },
  {
    id: 4,
    name: 'Co-Working Desk',
    description: 'Flexible co-working space with dedicated desk, high-speed internet, and access to all community amenities.',
    type: 'coworking',
    category: 'Co-Working Space',
    price: 299,
    priceUnit: 'month',
    capacity: 1,
    location: '321 Startup Lane, Nairobi - Runda',
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80',
    amenities: ['WiFi', 'Desk', 'Locker', 'Coffee', 'Meeting Room Access'],
    rating: 4.6,
    reviews: 67,
    available: true,
    featured: true,
  },
  {
    id: 5,
    name: 'Wellness Studio',
    description: 'Peaceful yoga and wellness studio with mirrored walls, hardwood floors, and serene atmosphere.',
    type: 'studio',
    category: 'Wellness Center',
    price: 50,
    priceUnit: 'hour',
    capacity: 20,
    location: '555 Peaceful Way, Nairobi - Karen',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
    amenities: ['WiFi', 'Yoga Mats', 'Sound System', 'Lockers', 'Showers'],
    rating: 4.9,
    reviews: 31,
    available: true,
    featured: false,
  },
{
    id: 6,
    name: 'Event Venue Hall',
    description: 'Elegant event venue perfect for weddings, parties, and corporate events. Fully customizable space.',
    type: 'event',
    category: 'Event Space',
    price: 2000,
    priceUnit: 'event',
    capacity: 200,
    location: '888 Celebration Blvd, Nairobi - CBD',
    image: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&q=80',
    amenities: ['WiFi', 'Catering Kitchen', 'Stage', 'Parking', 'Decoration Services'],
    rating: 4.8,
    reviews: 89,
    available: true,
    featured: true,
  },



